cors:
 originPatterns: http://localhost:3000,http://localhost:8000,http://localhost:8080
spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/rest_with_spring_boot
  username: root
  password: root123
 jpa:
  open-in-view: true
  hibernate:
   ddl-auto: none
   #properties:
   # hibernate:
    #dialect: org.hibernate.dialect.MySQLDialect
  show-sql: false
springdoc:
 api-docs:
  path: /api-docs
 swagger-ui:
  path: /swagger-ui.html
  use-root-path: true
 paths-to-match: /api/**