cors:
 originPatterns: http://localhost:3000,http://localhost:8000,http://localhost:8080
file:
 upload-dir: C:/Users/Administrator/Documents/UploadDir
security:
 jwt:
  token:
   secret-key: 53cr37
   expire-length: 3600000
spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/rest_with_spring_boot
  username: root
  password: root123
 jpa:
  open-in-view: true
  hibernate:
   ddl-auto: update
  show-sql: false
 servlet:
  multipart:
   enabled: true
   file-size-threshold: 2KB
   max-file-size: 200MB
   max-request-size: 215MB
 flyway:
  baseline-on-migrate: true
springdoc:
 api-docs:
  path: /api-docs
 swagger-ui:
  use-root-path: true
 paths-to-match:
  - /auth/**
  - /api/**